![](../img/samplings1.png)

# 越大越好

In [2]:
import numpy as np

In [2]:
# prob_dist为一个样本预测的概率分布
prob_dist = np.array([0.9352784428596497, 0.05409964170306921, 0.038225741147994995])

#### Least Confidence
* 概率最大的值也比较小
* difference between the most confident prediction and 100% confidence
* 使用LC会倾向于选择长句子

In [3]:
most_conf = np.nanmax(prob_dist)    # Return the maximum of an array
num_labels = prob_dist.size
numerator = (num_labels * (1 - most_conf))    # 1-最大的标签概率值
denominator = (num_labels - 1)

least_conf = numerator/denominator
print(least_conf)    # 0.09708233571052549

0.09708233571052549


#### Margin of confidence sampling
* 概率最大的两个值差距不是很明显
* difference between the top two most confident predictions

In [13]:
# prob_dist[::-1].sort()
difference = prob_dist[0] - prob_dist[1]    # 最大值减去第二大值

margin_conf = 1 - difference
print(margin_conf)    # 0.11882119884341957

0.11882119884341957


#### Ratio of Confidence
* 概率最大的两个值差距不是很明显
* ratio between the top two most confident predictions

In [14]:
ratio_conf = prob_dist[1] / prob_dist[0]    # 最大值/第二大值
print(ratio_conf)    # 17.28807092647693

17.28807092647693


#### Entropy Sampling
* 选择熵大的
* difference between all predictions, as defined by information theory

In [15]:
prbs_logs = prob_dist * np.log2(prob_dist)
numerator = 0 - np.sum(prbs_logs)
denominator = np.log2(prob_dist.size)

entropy = numerator/denominator
print(entropy)    # 0.31418125050963064

0.31418125050963064


#### Maximum Normalized Log-Probality（MNLP）
* 最大归一化对数概率方法(针对序列标注问题)
* 参考文献：DEEP ACTIVE LEARNING FOR NAMED ENTITY RECOGNITION(Yanyao Shen,2017)

In [4]:
import torch
import numpy as np
logists = np.random.random(size=(3,4))    # 序列长度为3,  4分类
print(logists)
np.sum(np.log(logists.max(-1)[0]))/logists.shape[0]

[[0.31158052 0.85954846 0.63839036 0.11348048]
 [0.57505734 0.26914474 0.19712184 0.82477003]
 [0.13871147 0.88584413 0.02020741 0.05100702]]


-0.050449357960654494

In [1]:
import torch
import numpy as np
logists = np.random.random(size=(2,3))    # 序列长度为3,  每个token分成4类
print(logists)
np.sum(np.log(logists.max(-1)[0]))/logists.shape[0]

d:\Anaconda\envs\tor1131py37\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[[0.92593499 0.81605101 0.1933146 ]
 [0.70379191 0.6296827  0.97240277]]


-0.038475625928334915