![](../img/samplings1.png)

In [2]:
import numpy as np

In [2]:
# prob_dist为一个样本预测的概率分布
prob_dist = np.array([0.9352784428596497, 0.05409964170306921, 0.038225741147994995])

#### Least Confidence
* difference between the most confident prediction and 100% confidence
* 使用LC会倾向于选择长句子

In [3]:
most_conf = np.nanmax(prob_dist)    # Return the maximum of an array
num_labels = prob_dist.size
numerator = (num_labels * (1 - most_conf))    # 1-最大的标签概率值
denominator = (num_labels - 1)

least_conf = numerator/denominator
print(least_conf)    # 0.09708233571052549

0.09708233571052549


#### Margin of confidence sampling
difference between the top two most confident predictions

In [13]:
# prob_dist[::-1].sort()
difference = prob_dist[0] - prob_dist[1]    # 最大值减去第二大值

margin_conf = 1 - difference
print(margin_conf)    # 0.11882119884341957

0.11882119884341957


#### Ratio of Confidence
ratio between the top two most confident predictions

In [14]:
ratio_conf = prob_dist[0] / prob_dist[1]    # 最大值/第二大值
print(ratio_conf)    # 17.28807092647693

17.28807092647693


#### Entropy Sampling
difference between all predictions, as defined by information theory

In [15]:
prbs_logs = prob_dist * np.log2(prob_dist)
numerator = 0 - np.sum(prbs_logs)
denominator = np.log2(prob_dist.size)

entropy = numerator/denominator
print(entropy)    # 0.31418125050963064

0.31418125050963064


#### Maximum Normalized Log-Probality（MNLP）
* 最大归一化对数概率方法(针对序列标注问题)
* 参考文献：DEEP ACTIVE LEARNING FOR NAMED ENTITY RECOGNITION(Yanyao Shen,2017)

In [15]:
import torch
d = np.random.random(size=(3,4))    # 序列长度为3,4分类
print(d)
np.sum(np.log(d.max(-1)[0]))/d.shape[0]

[[0.78952317 0.35976435 0.96838048 0.94464513]
 [0.09198099 0.52867963 0.06529253 0.43732983]
 [0.83175306 0.46120938 0.97753297 0.59415624]]


-0.01071007116257311